spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/kakaopay
    driver-class-name: org.mariadb.jdbc.Driver
    username: junyoung
    password: wnsdud@123

  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
#   org.hibernate.type: trace
